//! Workflow optimization suggestions.
//!
//! Based on the detected fixed points and universality class:
//!
//! - **Fixed point (stuck in a rut)** → suggest automation
//! - **Exploratory (no convergence)** → suggest documentation
//! - **Transitioning (exponent changing)** → note the shift: "Your workflow just changed — new project?"

use super::fixed_point::FixedPoint;
use super::universality::{UniversalityClass, CriticalExponent};

/// The kind of suggestion being made.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SuggestionKind {
    /// Automate a repetitive workflow.
    Automate,
    /// Document an exploratory workflow for future reference.
    Document,
    /// Note a workflow transition.
    TransitionNote,
    /// Skill consolidation — you're getting better at this.
    Encouragement,
    /// Deep learning detected — this is a hard-won skill.
    DeepSkill,
}

impl std::fmt::Display for SuggestionKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Automate => write!(f, "automate"),
            Self::Document => write!(f, "document"),
            Self::TransitionNote => write!(f, "transition"),
            Self::Encouragement => write!(f, "encouragement"),
            Self::DeepSkill => write!(f, "deep-skill"),
        }
    }
}

/// A single suggestion generated by the analysis.
#[derive(Debug, Clone, PartialEq)]
pub struct Suggestion {
    /// What kind of suggestion this is.
    pub kind: SuggestionKind,
    /// Human-readable suggestion text.
    pub message: String,
    /// The command(s) this suggestion relates to (if any).
    pub related_commands: Vec<String>,
    /// Priority: 0 = informational, 1 = worth mentioning, 2 = strong recommendation.
    pub priority: u8,
}

/// Generates suggestions based on skill detection results.
#[derive(Debug, Clone)]
pub struct SuggestionEngine {
    /// Minimum quality score for a fixed point to warrant automation.
    automation_threshold: f64,
    /// Minimum survival length for deep-skill recognition.
    deep_skill_threshold: usize,
}

impl SuggestionEngine {
    pub fn new() -> Self {
        Self {
            automation_threshold: 0.5,
            deep_skill_threshold: 3,
        }
    }

    /// Generate suggestions from detected skills, universality class, and exponent.
    pub fn generate(
        &self,
        skills: &[FixedPoint],
        class: &UniversalityClass,
        exponent: &CriticalExponent,
    ) -> Vec<Suggestion> {
        let mut suggestions = Vec::new();

        // 1. Automate fixed points with high quality scores
        for skill in skills {
            if skill.quality() > self.automation_threshold && skill.active {
                suggestions.push(Suggestion {
                    kind: SuggestionKind::Automate,
                    message: format!(
                        "You've been running '{}' extensively — consider creating a script or alias for it.",
                        skill.command
                    ),
                    related_commands: vec![skill.command.clone()],
                    priority: 2,
                });
            }
        }

        // 2. Class-based suggestions
        match class {
            UniversalityClass::Mechanical => {
                suggestions.push(Suggestion {
                    kind: SuggestionKind::Automate,
                    message: "Your workflow is purely mechanical — this should be automated entirely.".to_string(),
                    related_commands: skills.iter().map(|s| s.command.clone()).collect(),
                    priority: 2,
                });
            }
            UniversalityClass::BuildHeavy => {
                suggestions.push(Suggestion {
                    kind: SuggestionKind::Automate,
                    message: "Build-heavy workflow detected: repetitive pattern, fast convergence. Great candidate for a Makefile or CI pipeline.".to_string(),
                    related_commands: vec![],
                    priority: 1,
                });
            }
            UniversalityClass::DebugHeavy => {
                suggestions.push(Suggestion {
                    kind: SuggestionKind::Document,
                    message: "Debug-heavy workflow: you're doing structured exploration. Documenting your debugging process would help future-you and teammates.".to_string(),
                    related_commands: vec![],
                    priority: 1,
                });
            }
            UniversalityClass::Exploratory => {
                suggestions.push(Suggestion {
                    kind: SuggestionKind::Document,
                    message: "Exploratory workflow: no fixed pattern yet. Consider writing notes on what you find — you're in discovery mode.".to_string(),
                    related_commands: vec![],
                    priority: 0,
                });
            }
            UniversalityClass::Transitioning => {
                suggestions.push(Suggestion {
                    kind: SuggestionKind::TransitionNote,
                    message: "Your workflow just changed — new project? I'll keep watching to learn your new patterns.".to_string(),
                    related_commands: vec![],
                    priority: 1,
                });
            }
        }

        // 3. Deep skill recognition
        for skill in skills {
            if skill.survival_length >= self.deep_skill_threshold {
                let plateau_time = class.predicted_plateau_time();
                let msg = if plateau_time.is_finite() {
                    format!(
                        "Deep skill detected: '{}' survived {} levels of coarse-graining. Based on your universality class ({}), you'll fully plateau in ~{:.0} days.",
                        skill.command,
                        skill.survival_length,
                        class,
                        plateau_time,
                    )
                } else {
                    format!(
                        "Deep skill detected: '{}' survived {} levels of coarse-graining. Your exploratory workflow means you may never plateau — and that's OK.",
                        skill.command,
                        skill.survival_length,
                    )
                };

                suggestions.push(Suggestion {
                    kind: SuggestionKind::DeepSkill,
                    message: msg,
                    related_commands: vec![skill.command.clone()],
                    priority: 1,
                });
            }
        }

        // 4. Encouragement for converging workflows
        if exponent.value > 0.0 && exponent.confidence > 0.5 {
            suggestions.push(Suggestion {
                kind: SuggestionKind::Encouragement,
                message: format!(
                    "Your workflow is converging (exponent = {:.2}). You're building a stable skill set.",
                    exponent.value,
                ),
                related_commands: vec![],
                priority: 0,
            });
        }

        // Sort by priority (highest first) and deduplicate by kind+message
        suggestions.sort_by(|a, b| b.priority.cmp(&a.priority));

        let mut seen = std::collections::HashSet::new();
        suggestions.retain(|s| seen.insert((s.kind, s.message.clone())));

        suggestions
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_fixed_point(command: &str, quality: f64, survival: usize, active: bool) -> FixedPoint {
        FixedPoint {
            command: command.to_string(),
            first_fixed_level: 1,
            survival_length: survival,
            frequency: quality,
            active,
        }
    }

    #[test]
    fn mechanical_class_triggers_automation() {
        let engine = SuggestionEngine::new();
        let suggestions = engine.generate(
            &[make_fixed_point("make", 0.9, 4, true)],
            &UniversalityClass::Mechanical,
            &CriticalExponent::new(0.2, 0.8),
        );
        assert!(suggestions.iter().any(|s| s.kind == SuggestionKind::Automate));
    }

    #[test]
    fn exploratory_class_triggers_documentation() {
        let engine = SuggestionEngine::new();
        let suggestions = engine.generate(
            &[],
            &UniversalityClass::Exploratory,
            &CriticalExponent::new(2.0, 0.8),
        );
        assert!(suggestions.iter().any(|s| s.kind == SuggestionKind::Document));
    }

    #[test]
    fn transitioning_class_triggers_transition_note() {
        let engine = SuggestionEngine::new();
        let suggestions = engine.generate(
            &[],
            &UniversalityClass::Transitioning,
            &CriticalExponent::new(-1.0, 0.5),
        );
        assert!(suggestions.iter().any(|s| s.kind == SuggestionKind::TransitionNote));
    }

    #[test]
    fn high_quality_skill_triggers_automation() {
        let engine = SuggestionEngine::new();
        let fp = make_fixed_point("cargo build", 0.9, 2, true);
        let suggestions = engine.generate(
            &[fp],
            &UniversalityClass::BuildHeavy,
            &CriticalExponent::new(0.5, 0.8),
        );
        assert!(suggestions.iter().any(|s| {
            s.kind == SuggestionKind::Automate && s.related_commands.contains(&"cargo build".to_string())
        }));
    }

    #[test]
    fn low_quality_skill_no_automation() {
        let engine = SuggestionEngine::new();
        let fp = make_fixed_point("rare_cmd", 0.1, 1, true);
        let suggestions = engine.generate(
            &[fp],
            &UniversalityClass::Exploratory,
            &CriticalExponent::new(2.0, 0.8),
        );
        // No automation suggestion for low-quality fixed point
        let auto_for_rare = suggestions.iter().any(|s| {
            s.kind == SuggestionKind::Automate && s.related_commands.contains(&"rare_cmd".to_string())
        });
        assert!(!auto_for_rare);
    }

    #[test]
    fn deep_skill_recognition() {
        let engine = SuggestionEngine::new();
        let fp = make_fixed_point("vim", 0.8, 5, true);
        let suggestions = engine.generate(
            &[fp],
            &UniversalityClass::DebugHeavy,
            &CriticalExponent::new(1.0, 0.8),
        );
        assert!(suggestions.iter().any(|s| s.kind == SuggestionKind::DeepSkill));
    }

    #[test]
    fn deep_skill_with_infinite_plateau() {
        let engine = SuggestionEngine::new();
        let fp = make_fixed_point("explore", 0.7, 4, true);
        let suggestions = engine.generate(
            &[fp],
            &UniversalityClass::Exploratory,
            &CriticalExponent::new(2.0, 0.8),
        );
        let deep = suggestions.iter().find(|s| s.kind == SuggestionKind::DeepSkill);
        assert!(deep.is_some());
        assert!(deep.unwrap().message.contains("never plateau"));
    }

    #[test]
    fn encouragement_for_converging() {
        let engine = SuggestionEngine::new();
        let suggestions = engine.generate(
            &[],
            &UniversalityClass::BuildHeavy,
            &CriticalExponent::new(0.5, 0.8),
        );
        assert!(suggestions.iter().any(|s| s.kind == SuggestionKind::Encouragement));
    }

    #[test]
    fn no_encouragement_for_low_confidence() {
        let engine = SuggestionEngine::new();
        let suggestions = engine.generate(
            &[],
            &UniversalityClass::BuildHeavy,
            &CriticalExponent::new(0.5, 0.1),
        );
        assert!(!suggestions.iter().any(|s| s.kind == SuggestionKind::Encouragement));
    }

    #[test]
    fn suggestions_sorted_by_priority() {
        let engine = SuggestionEngine::new();
        let suggestions = engine.generate(
            &[make_fixed_point("cmd", 0.9, 5, true)],
            &UniversalityClass::DebugHeavy,
            &CriticalExponent::new(1.0, 0.8),
        );
        for window in suggestions.windows(2) {
            assert!(window[0].priority >= window[1].priority);
        }
    }

    #[test]
    fn no_duplicate_suggestions() {
        let engine = SuggestionEngine::new();
        let fps = vec![
            make_fixed_point("a", 0.9, 4, true),
            make_fixed_point("a", 0.9, 4, true),
        ];
        let suggestions = engine.generate(
            &fps,
            &UniversalityClass::BuildHeavy,
            &CriticalExponent::new(0.5, 0.8),
        );
        // Count automation suggestions for "a"
        let count = suggestions.iter()
            .filter(|s| s.kind == SuggestionKind::Automate && s.related_commands.contains(&"a".to_string()))
            .count();
        assert!(count <= 1);
    }

    #[test]
    fn suggestion_kind_display() {
        assert_eq!(format!("{}", SuggestionKind::Automate), "automate");
        assert_eq!(format!("{}", SuggestionKind::Document), "document");
        assert_eq!(format!("{}", SuggestionKind::TransitionNote), "transition");
    }

    #[test]
    fn debug_heavy_suggests_documentation() {
        let engine = SuggestionEngine::new();
        let suggestions = engine.generate(
            &[],
            &UniversalityClass::DebugHeavy,
            &CriticalExponent::new(1.0, 0.8),
        );
        assert!(suggestions.iter().any(|s| s.kind == SuggestionKind::Document));
    }

    #[test]
    fn inactive_fixed_point_no_automation() {
        let engine = SuggestionEngine::new();
        let fp = make_fixed_point("old_cmd", 0.9, 4, false);
        let suggestions = engine.generate(
            &[fp],
            &UniversalityClass::BuildHeavy,
            &CriticalExponent::new(0.5, 0.8),
        );
        let auto_for_old = suggestions.iter().any(|s| {
            s.kind == SuggestionKind::Automate && s.related_commands.contains(&"old_cmd".to_string())
        });
        assert!(!auto_for_old);
    }
}
